package errors

import (
	"io"
)

// DO NOT EDIT THIS FILE.

// Errors is an error returned by a multiwriter when there are errors with one
// or more of the writes. Errors will be in a one-to-one correspondence with
// the input elements; successful elements will have a nil entry.
//
// Should not be constructed if all entires are nil; in this case one should
// instead return just nil instead of a MultiError.
type Errors []error

// wantClosePipe is used for testing;
// it should contain the string: "io: read/write on closed pipe"
var wantClosePipe = io.ErrClosedPipe.Error()
